@extends('layouts.index')
@section('title', 'Welcome Page')

@section('content')

<style>
  body {
    position: relative;
    overflow: hidden; /* Disable scrollbars */
    padding: 0 !important;
    margin: 0 !important;
    background-color: black !important;
  }


  .logo{
    position: fixed !important;
    width: 150px !important;
   right: 10;
    z-index: 999 !important;

}







  /* Define fade-in and fade-out animations */
  @keyframes fadeIn {
    from {
      opacity: 0;
    }
    to {
      opacity: 1;
    }
  }

  @keyframes fadeOut {
    from {
      opacity: 1;
    }
    to {
      opacity: 0;
    }
  }



          @-webkit-keyframes slide-in-bck-center {
  0% {
    -webkit-transform: translateZ(600px);
            transform: translateZ(600px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}
@keyframes slide-in-bck-center {
  0% {
    -webkit-transform: translateZ(600px);
            transform: translateZ(600px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}


  /* Apply fade-in animation to the video element */
  .fade-in {
    -webkit-animation: puff-in-center 0.7s cubic-bezier(0.470, 0.000, 0.745, 0.715) both;
	        animation: puff-in-center 0.7s cubic-bezier(0.470, 0.000, 0.745, 0.715) both;
  }

  @-webkit-keyframes puff-in-center {
  0% {
    -webkit-transform: scale(2);
            transform: scale(2);
    -webkit-filter: blur(4px);
            filter: blur(4px);
    opacity: 0;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
@keyframes puff-in-center {
  0% {
    -webkit-transform: scale(2);
            transform: scale(2);
    -webkit-filter: blur(4px);
            filter: blur(4px);
    opacity: 0;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
  /* ----------------------------------------------
 * Generated by Animista on 2024-4-14 17:38:40
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation puff-out-center
 * ----------------------------------------
 */
@-webkit-keyframes puff-out-center {
  0% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(2);
            transform: scale(2);
    -webkit-filter: blur(4px);
            filter: blur(4px);
    opacity: 0;
  }
}
@keyframes puff-out-center {
  0% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(2);
            transform: scale(2);
    -webkit-filter: blur(4px);
            filter: blur(4px);
    opacity: 0;
  }
}

  /* Apply fade-out animation to the video element */
  .fade-out {
    -webkit-animation: puff-out-center 1s cubic-bezier(0.165, 0.840, 0.440, 1.000) both;
	        animation: puff-out-center 1s cubic-bezier(0.165, 0.840, 0.440, 1.000) both;
  }
    /* Apply fade-in animation to the body */


  /* Hide overflow */
  video {
    width: 100%;
    height: 100vh;
  }
  .logo{
    width: 200px !important;
    padding-top: 30px !important;
    padding-left: 60px !important;
  }

</style>
{{-- <div class="main-container"> --}}
  <img class="logo" src="assets/wcmc_logo_1.png" alt="">
@if ($slides->isEmpty())
<script>
  // Reload the page after a short delay
  setTimeout(function() {
    location.reload();
  }, 2000); // Adjust the delay time as needed
</script>
@else
  @foreach ($slides as $slide)
    <video id="player" autoplay muted class="fade-in">
      <source
        class="video_player"
        src="{{ asset('image_upload/' . $slide->file) }}"
        type="video/mp4"
      />
    </video>




  @endforeach
@endif


{{-- </div> --}}




<script>
  var videoPaths = [
    @foreach($slides as $slide)
      "{{ asset('image_upload/' . $slide->file) }}",
    @endforeach
  ];
  var currentVideoIndex = 0;
  var player = document.getElementById("player");

  // Hide default controls
  player.controls = false;

  player.addEventListener("ended", function () {
    // Add fade-out class
    player.classList.add("fade-out");

    setTimeout(function () {
      // Switch video
      currentVideoIndex = (currentVideoIndex + 1) % videoPaths.length;

      // If loop is completed, reload the page after a delay
      if (currentVideoIndex === 0) {
        // Add smooth fade-out effect before reload
        document.body.classList.add("fade-in"); // Add fade-in class to body
        setTimeout(function () {
          location.reload();
        }, 500); // Wait for the fade-out animation to complete
      } else {
        // Load next video
        player.src = videoPaths[currentVideoIndex];
        player.play();
        // Remove fade-out class
        player.classList.remove("fade-out");
      }
    }, 500); // Wait for the fade-out animation to complete
  });
</script>



@endsection
